<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-FE8I8AGL" failures="0" tests="5" name="com.qa.flights.tests.ItinerariesPageTest" time="0.006" errors="1" timestamp="2024-05-13T19:32:15 IST" skipped="4">
  <testcase classname="com.qa.flights.tests.ItinerariesPageTest" name="itinerariesPageSetUp" time="0.005">
    <error message="Cannot invoke &quot;com.qa.flights.pages.LoginPage.loginToApp(String, String)&quot; because &quot;this.loginPage&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.qa.flights.pages.LoginPage.loginToApp(String, String)" because "this.loginPage" is null
at com.qa.flights.tests.ItinerariesPageTest.itinerariesPageSetUp(ItinerariesPageTest.java:13)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- itinerariesPageSetUp -->
  <testcase classname="com.qa.flights.tests.ItinerariesPageTest" name="getItinerariesTitleTest" time="0.001">
    <skipped/>
  </testcase> <!-- getItinerariesTitleTest -->
  <testcase classname="com.qa.flights.tests.ItinerariesPageTest" name="userInfoDisplayTest" time="0.000">
    <skipped/>
  </testcase> <!-- userInfoDisplayTest -->
  <testcase classname="com.qa.flights.tests.ItinerariesPageTest" name="clickBackTest" time="0.000">
    <skipped/>
  </testcase> <!-- clickBackTest -->
  <testcase classname="com.qa.flights.tests.ItinerariesPageTest" name="verifyBackToHomeTest" time="0.000">
    <skipped/>
  </testcase> <!-- verifyBackToHomeTest -->
</testsuite> <!-- com.qa.flights.tests.ItinerariesPageTest -->
